site_name: Atheist Notes
theme: 
  name: material
nav:
 - Introduction: index.md
 - Problem of Evil : chapter1.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  custom_dir: theme
  logo: img/logo.svg
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate 

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jod35jon

              
plugins:
   - glightbox
   - search